### PR TITLE
Soft-Keyboard and scrollTo compensation with regard to scrollableHeader

### PR DESCRIPTION
**Pull request by daniel-prinsloo**
The correct offset value is calculated in the event that a soft-keyboard
is showing and a scrollableHeader is present. The scrollableHeaders
height is added to offset.

### CODE REVIEW

**Comment by mcasimir** [comment]
Awesome, I'll review that as soon as I'll have 5 mins

Il lun 8 ago 2016, 15:40 daniel-prinsloo <notifications@github.com> ha
scritto:

**Comment by mcasimir** [comment]
So it looks fine to me, sadly i had a tons of changes to merge and it broke your PR. Let me know if u have the time to rebase and re-push, otherwise i'll manually apply it.

**Comment by byronigoe** [comment]
What happened here?

I don't think this PR was a complete solution anyway. I think any call to scrollTo() would be off by the size of the scrollableHeader. Why not re-open #369 ?

**Comment by mcasimir** [comment]
It's ok for me to reopen. I'd like to hear some feedback from the author of the PR

**Pull request closed without merging**
