### PR TITLE
Fixes #407

### LINKED ISSUE #407: Need of ui-mobile-option : Would solve some problems.
Hello again.

Well, i started implementing the thing just to realise ```sensitiveArea``` is already an option for the release event.

Just need another option for ```$movementTarget``` and expose options for the directive.

### PR DESCRIPTION
**Pull request by Rouche**

### CODE REVIEW

**Comment by mcasimir** [comment]
Thanks i'll review that asap

Il lun 14 nov 2016, 18:05 Jean-Francois Larouche notifications@github.com
ha scritto:

**Comment by Rouche** [comment]
No local lint build. Sorry for spam :/

**Comment by Rouche** [comment]
Its fully tested now. I forgot a little detail for default behabior sorry.

Little note: i did not commit the dist directory since its done by ```gulp build``` but i was unsure if i need to.

**Comment by Rouche** [comment]
Hello!
Any updates? Is this project still maintained?

**Comment by mcasimir** [comment]
Hi, yes it is. I'll look into that today.

Il lun 16 gen 2017, 02:59 Jean-Francois Larouche <notifications@github.com>
ha scritto:

**Comment by Rouche** [comment]
Ill just continue on fork. Thanks a lot for the lib.

**Pull request closed without merging**
