### PR TITLE
Renamed `ui-state` to `ui-shared-state`

### PR DESCRIPTION
**Pull request by mcasimir**
Added `ui-shared-state` and **deprecated** `ui-state` so it does not clash with ui-router

### CODE REVIEW

**Comment by mcasimir** [comment]
@vkarampinis, @ryanannatuvasquez i can merge and release this next days. I'd like to hear your feedback if u have some time.

Does aliasing `ui-state` to `ui-shared-state` works as workaround?

**Comment by vkarampinis** [comment]
@mcasimir 👍

**Comment by ryanannatuvasquez** [comment]
@mcasimir 👍

**Comment by mkalpana** [comment]
@mcasimir :+1:

**Pull request merged**
